# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         pgtop
version:      0.05
version_from: pgtop
installdirs:  site
requires:
    DBD::Pg:                       1.22
    DBI:                           1.16
    Term::ReadKey:                 2.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
